// ============================================================
// events.js — ライブイベントデータ管理ファイル
// このファイルは管理ダッシュボードから自動生成されます。
// 手で編集しても構いませんが、下記の形式（各キー）を崩さないでください。
//   month:1〜12 / date:"7月5日（土）" / title / artist / time / charge /
//   description / image:"images/ファイル名.jpg"（画像なしは ""）
// ホームのスライドショーとイベントページが、このデータを共有して読み込みます。
// ============================================================

const KLAVIER_EVENTS = [
  {
    month: 5,
    date: "5月22日（金）",
    title: "Me-Know trio.",
    artist: "Me-Know trio. 井上尚彦(ds), 野口久和(pf) & 山村隆一(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 5,
    date: "5月23日（土）",
    title: "塚山エリコ trio",
    artist: "塚山エリコ(pf), 斉藤クジラ誠(b) & 市原康(ds)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥4,000",
    description: "",
    image: "",
  },
  {
    month: 5,
    date: "5月29日（金）",
    title: "谷口英治 & 土田晴信",
    artist: "谷口英治(cl) & 土田晴信(p)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 5,
    date: "5月30日（土）",
    title: "小林陽一JJM",
    artist: "小林陽一JJM太田寛二(pf), 栗山勇輝(tp), 櫻井智則(ts) & 安田幸司(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥4,000",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月5日（金）",
    title: "里見紀子 & 森下滋",
    artist: "里見紀子(vl) & 森下滋(p)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月6日（土）",
    title: "New Standars Quintet",
    artist: "New Standars Quintet. 木村由紀夫(ds), 須藤俊也(p), 山田晃路(b), 右近茂(sax) & 駒野逸美(tb)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,900",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月12日（金）",
    title: "山川秀明 trio",
    artist: "山川秀明(vo,p), 滝沢ミナコ(fl) & 山口友生(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月19日（金）",
    title: "鈴木良雄 & 榊原太郎",
    artist: "鈴木良雄(p), 榊原太郎(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月20日（土）",
    title: "嶋津健一 & 加藤真一",
    artist: "嶋津健一(p) & 加藤真一(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月26日（金）",
    title: "久米雅之 quartet",
    artist: "久米雅之(ds), 加藤友彦(p), 石川隆一(b) & 江澤茜(sax)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,500",
    description: "",
    image: "",
  },
  {
    month: 6,
    date: "6月27日（土）",
    title: "向井滋春 trio",
    artist: "向井滋春(tb), 河上修(b) & 小沢咲希(p)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月3日(金)",
    title: "佐藤節雄d,吉岡秀晃p &横山裕b。",
    artist: "佐藤節雄d,吉岡秀晃p &横山裕b",
    time: "OPEN 19:00/START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "７月４日(土)",
    title: "川嶋哲郎sax,熊谷ヤスマサp &本川悠平b",
    artist: "川嶋哲郎sax,熊谷ヤスマサp &本川悠平b",
    time: "OPEN 7:00/START 7:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月10日(金)",
    title: "クラヴィエールSuper Jam Session,vol 4",
    artist: "関根敏行p &水橋孝b",
    time: "OPEN 19:00/START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月11日(土)",
    title: "Vocal Jam Session.神村晃司p &堀江大輔b",
    artist: "神村晃司p &堀江大輔b",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "ﾌﾟﾛﾐｭｰｼﾞｼｬﾝはゲスト扱いです。",
    image: "",
  },
  {
    month: 7,
    date: "🈵7月17日(金)",
    title: "🈵豊田チカ,田中裕士p,水橋孝b & 小山太郎d",
    artist: "豊田チカ,田中裕士p,水橋孝b & 小山太郎d",
    time: "OPEN 19:00/ START 19:30",
    charge: "¥3,900",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月18日(土)",
    title: "高瀬龍一tp,平岡遊一郎g &続木徹p",
    artist: "高瀬龍一tp,平岡遊一郎g &続木徹p",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月24日(金)",
    title: "井上祐一p,本川悠平b &田村陽介d ",
    artist: "井上祐一p,本川悠平b &田村陽介d ",
    time: "OPEN 19:00/START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 7,
    date: "7月25日(土)",
    title: "杉本篤彦g, 進藤陽悟p",
    artist: "杉本篤彦g, 進藤陽悟p",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "8 月１日",
    title: "井上智(g)石田衛(p)増原巌(b)",
    artist: "井上智(g)石田衛(p)増原巌(b)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月７日",
    title: "休み",
    artist: "休み",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月８日",
    title: "休み",
    artist: "休み",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月１４日",
    title: "谷口英治(p)鈴木洋一(g)土田晴信(org)",
    artist: "谷口英治(p)鈴木洋一(g)土田晴信(org)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月１５日",
    title: "板垣光弘(p)大月裕信(b)関根豊明(ds)",
    artist: "板垣光弘(p)大月裕信(b)関根豊明(ds)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月１５日",
    title: "板垣光弘(p)大月裕信(b)関根豊明(ds)",
    artist: "板垣光弘(p)大月裕信(b)関根豊明(ds)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月２１日",
    title: "豊田チカ(vo)川嶋哲郎(ts)🈵",
    artist: "豊田チカ(vo)川嶋哲郎(ts) ありがとうございます満員御礼となりました 。",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月２２日",
    title: "河上修(b)吉永絢香(sax)",
    artist: "河上修(b)吉永絢香(sax)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月２８日",
    title: "近藤和彦(as)市川秀男(p)",
    artist: "近藤和彦(as)市川秀男(p)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 8,
    date: "８月２９日",
    title: "三木俊雄(ts)石田衛(p)",
    artist: "三木俊雄(ts)石田衛(p)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
  {
    month: 9,
    date: "９月４日",
    title: "岡安芳明(gt)&安保徹(sax)",
    artist: "岡安芳明(gt)&安保徹(sax)",
    time: "OPEN 19:00 / START 19:30",
    charge: "¥3,000",
    description: "",
    image: "",
  },
];

// ============================================================
// 【重要】以下のヘルパー関数は main.js から呼び出されます。
//         これが無いとイベントページとスライドショーが表示されません。
//         ダッシュボードが保存のたびに自動で書き出します（削除しないでください）。
// ============================================================

// 指定した月のイベントだけを返す
function getEventsByMonth(month) {
  return KLAVIER_EVENTS.filter(event => event.month === month);
}

// 日本時間（UTC+9）で「今月」のイベントを返す
function getCurrentMonthEvents() {
  const nowJST = new Date(Date.now() + 9 * 60 * 60 * 1000);
  const currentMonth = nowJST.getUTCMonth() + 1;
  return getEventsByMonth(currentMonth);
}

// 日本時間の「今月」の月番号を返す（1〜12）
function getCurrentMonthNumber() {
  const nowJST = new Date(Date.now() + 9 * 60 * 60 * 1000);
  return nowJST.getUTCMonth() + 1;
}
